#!/bin/bash

. $HOME/.bashrc

swaycmd() {
    swaymsg "$@" &>/dev/null
    sleep 0.5
}

sleepcmd() {
    "$@" &>/dev/null &
    sleep 0.8
}


swaycmd "workspace 1"
sleepcmd $TERMINAL
swaycmd "workspace 2"
sleepcmd firefox
swaycmd "workspace 3"
sleepcmd bash -i -c "em"
sleepcmd $TERMINAL
swaycmd layout stacking
swaycmd "workspace 4"
sleepcmd teams-run
sleepcmd zulip
sleepcmd outlook-run
swaycmd layout stacking


