#!/bin/sh

export TERMINAL="alacritty"
export BROWSER="firefox"
export EDITOR="emacs"
export XDG_CURRENT_DESKTOP="sway"
export XDG_SESSION_TYPE="wayland"
export XDG_SCREENSHOTS_DIR=~/Pictures/screenshots
export QT_QPA_PLATFORM="wayland"
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export CLUTTER_BACKEND="wayland"
export SDL_VIDEODRIVER="wayland"
# export GDK_BACKEND="wayland"
export MOZ_ENABLE_WAYLAND=1
export MOZ_ENABLE_WAYLAND=1
export MOZ_WEBRENDER=1
export MOZ_ACCELERATED=1
export MOZ_DBUS_REMOTE=1

export _JAVA_AWT_WM_NONREPARENTING=1

for i in /dev/dri/card*; do
    is_integrated=$(udevadm info -a -n $i 2>/dev/null | grep boot_vga | rev | cut -c 2)
    if [ ! -z "$is_integrated" ]; then
        WLR_DRM_DEVICES="$i" sway
        exit 0
    fi
done

sway
